
#Összes kikötőhely lekérdezése
GET http://localhost:8080/api/berths
Accept: application/json

###

#Paraméterezett lekérdezés / szűrés kikötő nevére
GET http://localhost:8080/api/berths?town=badacsony
Accept: application/json

###

#Paraméterezett lekérdezés / szűrés kikötőhely szélességre
GET http://localhost:8080/api/berths?width=310
Accept: application/json

###

#Paraméterezett lekérdezés / szűrés kikötő nevére és kikötőhely szélességre
GET http://localhost:8080/api/berths?width=310&town=badacsony
Accept: application/json

###

#Kikötőhely ID szerinti lekérdezés
GET http://localhost:8080/api/berths/1
Accept: application/json
###



#Kikötőhely ID szerinti módosítása
PUT http://localhost:8080/api/berths/1
Content-Type: application/json
Accept: application/json

{
  "code": "JJU7",
  "length": 1100,
  "width": 350,
  "berthType": "POWER_WATER_WIFI"
}
###

#Kikötőhely ID szerinti törlése
DELETE http://localhost:8080/api/berths/1
Accept: application/json
###


#Foglalás hozzáadása hozzáadásat ID alapján
POST http://localhost:8080/api/berths/1/bookings
Content-Type: application/json
Accept: application/json

{
  "boatName": "Flyer",
  "registrationNumber": "h45445",
  "boatLength":710,
  "boatWidth": 245,
  "fromDate": "2022-10-12",
  "numberOfDays":3
}
###


