

GET http://localhost:8080/api/berths
Accept: application/json

###

GET http://localhost:8080/api/berths/21
Accept: application/json
###

DELETE http://localhost:8080/api/berths/20
Accept: application/json
###

PUT http://localhost:8080/api/berths/6
Content-Type: application/json
Accept: application/json

{
  "code": "JJU7",
  "length": 800,
  "width": 320,
  "berthType": "POWER_WATER_WIFI"
}
###

POST http://localhost:8080/api/berths/1
Content-Type: application/json
Accept: application/json

{
  "boatName": "Flyeeer",
  "registrationNumber": "h45445",
  "boatLength":620,
  "boatWidth": 150,
  "fromDate": "2022-07-17",
  "numberOfDays":3
}

###
GET http://localhost:8080/api/berths?width=380&portName=badacsony
Accept: application/json

###
GET http://localhost:8080/api/berths?portName=badacsony
Accept: application/json

###
GET http://localhost:8080/api/berths?width=380
Accept: application/json

###
GET http://localhost:8080/api/berths
Accept: application/json

###