

GET http://localhost:8080/api/berths
Accept: application/json

###

GET http://localhost:8080/api/berths/10
Accept: application/json
###

DELETE http://localhost:8080/api/berths/20
Accept: application/json
###