#Kikötő létrehozása
POST http://localhost:8080/api/ports
Content-Type: application/json
Accept: application/json

{
  "portName": "Badacsony",
  "email": "badacsony@balaport.hu",
  "numberOfGuestBerths": 6
}
###

#Összes kikötő lekérdezése
GET http://localhost:8080/api/ports
Accept: application/json

###

#Kikötő ID szerinti lekérdezés
GET http://localhost:8080/api/ports/1
Accept: application/json

###

#Paraméterezett lekérdezés / szűrés kikötő nevére
GET http://localhost:8080/api/ports?name=badacsony
Accept: application/json
###

#Paraméterezett lekérdezés / szűrés kapacitásra
GET http://localhost:8080/api/ports?capacity=5
Accept: application/json
###

#Paraméterezett lekérdezés / szűrés kikötő nevére és kapacitásra
GET http://localhost:8080/api/ports?capacity=3&name=badacsony
Accept: application/json

###

#Kikötő módosítása ID alapján
PUT http://localhost:8080/api/ports/1
Content-Type: application/json
Accept: application/json

{
  "numberOfGuestBerths": 15
}

###

#Kikötő törlése ID alapján
DELETE http://localhost:8080/api/ports/1
Accept: application/json

###

#Kikötőhely hozzáadásat ID alapján
POST http://localhost:8080/api/ports/1/berths
Content-Type: application/json
Accept: application/json

{
  "code": "PW-I",
  "length": 11000,
  "width": 320,
  "berthType": "POWER_WATER"
}
###