POST http://localhost:8080/api/ports
Content-Type: application/json
Accept: application/json

{
  "portName": "Badacsonnnnny",
  "email": "badacsony@balaport.hu",
  "numberOfGuestBerths": 5
}

###
GET http://localhost:8080/api/ports/1
Accept: application/json
###

GET http://localhost:8080/api/ports
Accept: application/json
###
